version: 2

updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "14:00"
      timezone: "Asia/Tokyo"
    reviewers:
      - "increments/qiita-dev-group"
