name: Notify Slack

on:
  discussion_comment:
    types: [created]
jobs:
  notify_creation_of_discussions:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    if: github.event.discussion && github.event.comment
    steps:
      - uses: slackapi/slack-github-action@485a9d42d3a73031f12ec201c457e2162c45d02d # v2.0.0
        with:
          method: chat.postMessage
          payload: |
            channel: "${{ secrets.SLACK_CHANNEL_ID }}"
            text: "Created discussion comment: ${{ github.event.comment.html_url }}"
        env:
          SLACK_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
